
os: linux
dist: focal

language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.15.0-focal
  - sudo apt update -qq

install:
  # install CMake
  - sudo apt install -qq cmake
  - cmake -version
  
  # Dependency for Qt
  - sudo apt install -qq mesa-common-dev libglu1-mesa-dev
  
  # Install Qt
  - sudo apt install -qq qt515base qt515serialbus

  # Setup Qt env
  - source /opt/qt*/bin/qt*-env.sh

script:
  - cmake .
  - make -j$(nproc)
