version: '{branch}_{build}'
image: Visual Studio 2019

platform:
  - x64

install:
  - cmd: set PATH=C:\Qt\5.15\mingw81_64\bin;%PATH%
#  - cmd: windeployqt.exe (return code isn't correct)
  
  - cmd: set PATH=C:\Qt\Tools\mingw810_64\bin;%PATH%
  - cmd: g++ -v

  # Remove git sh.exe from PATH (required for CMAKE)
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: cmake --version
  
  - cmd: echo %PATH%

build_script:
  - cmd: mkdir build
  - cmd: cd build
  
  - cmd: cmake .. -G "MinGW Makefiles"
  - cmd: mingw32-make -j2

  - cmd: mkdir deploy
  - cmd: copy ModbusTestSlave.exe deploy
  - cmd: cd deploy
  - cmd: windeployqt.exe ModbusTestSlave.exe --compiler-runtime -verbose 2
  
  # Back to build dir
  - cmd: cd ..
  
  - cmd: 7z a ModbusTestSlave.zip ".\deploy\*"

artifacts:
 - path: build\ModbusTestSlave.zip
